<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'AWeberAPI' => $vendorDir . '/aweber/aweber/aweber_api/aweber.php',
    'AWeberAPIBase' => $vendorDir . '/aweber/aweber/aweber_api/aweber.php',
    'AWeberAPIException' => $vendorDir . '/aweber/aweber/aweber_api/exceptions.php',
    'AWeberCollection' => $vendorDir . '/aweber/aweber/aweber_api/aweber_collection.php',
    'AWeberEntry' => $vendorDir . '/aweber/aweber/aweber_api/aweber_entry.php',
    'AWeberEntryDataArray' => $vendorDir . '/aweber/aweber/aweber_api/aweber_entry_data_array.php',
    'AWeberException' => $vendorDir . '/aweber/aweber/aweber_api/exceptions.php',
    'AWeberMethodNotImplemented' => $vendorDir . '/aweber/aweber/aweber_api/exceptions.php',
    'AWeberOAuthAdapter' => $vendorDir . '/aweber/aweber/aweber_api/oauth_adapter.php',
    'AWeberOAuthDataMissing' => $vendorDir . '/aweber/aweber/aweber_api/exceptions.php',
    'AWeberOAuthException' => $vendorDir . '/aweber/aweber/aweber_api/exceptions.php',
    'AWeberResourceNotImplemented' => $vendorDir . '/aweber/aweber/aweber_api/exceptions.php',
    'AWeberResponse' => $vendorDir . '/aweber/aweber/aweber_api/aweber_response.php',
    'AWeberResponseError' => $vendorDir . '/aweber/aweber/aweber_api/exceptions.php',
    'AWeberServiceProvider' => $vendorDir . '/aweber/aweber/aweber_api/aweber.php',
    'CurlInterface' => $vendorDir . '/aweber/aweber/aweber_api/curl_object.php',
    'CurlObject' => $vendorDir . '/aweber/aweber/aweber_api/curl_object.php',
    'CurlResponse' => $vendorDir . '/aweber/aweber/aweber_api/curl_response.php',
    'OAuthApplication' => $vendorDir . '/aweber/aweber/aweber_api/oauth_application.php',
    'OAuthServiceProvider' => $vendorDir . '/aweber/aweber/aweber_api/oauth_application.php',
    'OAuthUser' => $vendorDir . '/aweber/aweber/aweber_api/oauth_application.php',
);
